package org.themoviedb.auth;

public class AuthConstants {
    public static final String USER_API_KEY = "0e5daa2178c90def9e5c6f08e6318bee";
    public static final String USER_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwZTVkYWEyMTc4YzkwZGVmOWU1YzZmMDhlNjMxOGJlZSIsInN1YiI6IjYyZjY3OWFkNDk4YmMyMDA4NGZhMjhlZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.YRRAXhgrhHntHUVlakClX-OSqIq4g75Lx35H83erIhI";
    public static final String USER_REQUEST_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwZTVkYWEyMTc4YzkwZGVmOWU1YzZmMDhlNjMxOGJlZSIsImp0aSI6NDg2NDMwMSwic2NvcGVzIjpbInBlbmRpbmdfcmVxdWVzdF90b2tlbiJdLCJleHAiOjE2NjI1Nzg1MDEsInJlZGlyZWN0X3RvIjpudWxsLCJ2ZXJzaW9uIjoxLCJuYmYiOjE2NjI1Nzc2MDF9.KwMgjB3jWX5ohXKeaAMXCteez_iVTvbimxbHIkiLa80";
    public static final String USER_APP_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmY2NzlhZDQ5OGJjMjAwODRmYTI4ZWQiLCJhdWQiOiIwZTVkYWEyMTc4YzkwZGVmOWU1YzZmMDhlNjMxOGJlZSIsImp0aSI6IjQ4NjQzMDEiLCJzY29wZXMiOlsiYXBpX3JlYWQiLCJhcGlfd3JpdGUiXSwidmVyc2lvbiI6MSwibmJmIjoxNjYyNTc3ODc5fQ.gYDBKQKN_iBJY81MJg0etP9Vq6qXJK8fyn0ZyyUCy9Y";
}
