package org.themoviedb.auth;

public class AuthConstants {
    public static final String USER_API_KEY = "0e5daa2178c90def9e5c6f08e6318bee";
    public static final String USER_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwZTVkYWEyMTc4YzkwZGVmOWU1YzZmMDhlNjMxOGJlZSIsInN1YiI6IjYyZjY3OWFkNDk4YmMyMDA4NGZhMjhlZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.YRRAXhgrhHntHUVlakClX-OSqIq4g75Lx35H83erIhI";
    public static final String USER_REQUEST_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZXMiOlsicGVuZGluZ19yZXF1ZXN0X3Rva2VuIl0sImV4cCI6MTY2MjUwMzgxMCwicmVkaXJlY3RfdG8iOm51bGwsInZlcnNpb24iOjEsIm5iZiI6MTY2MjUwMjkxMCwiYXVkIjoiMGU1ZGFhMjE3OGM5MGRlZjllNWM2ZjA4ZTYzMThiZWUiLCJqdGkiOjQ4NjAzODJ9.IN_qQ8egC-b3X5cJXFsT1s6_u4oDwBHUsf01vMwdGBY";
    public static final String USER_APP_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmY2NzlhZDQ5OGJjMjAwODRmYTI4ZWQiLCJuYmYiOjE2NjI1MDQ0NzcsImF1ZCI6IjBlNWRhYTIxNzhjOTBkZWY5ZTVjNmYwOGU2MzE4YmVlIiwianRpIjoiNDg2MDM4MiIsInNjb3BlcyI6WyJhcGlfcmVhZCIsImFwaV93cml0ZSJdLCJ2ZXJzaW9uIjoxfQ.1wvfUP6M0x4kuEd5crq_jnPquBEjbhOh-KOUvkVJlYw";
}
